# 유저테이블 생성
CREATE TABLE PUBLIC.TODO_USERS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERS_ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT TODO_USERS_PK PRIMARY KEY (ID)
);

# 카테고리 테이블 생성
CREATE TABLE PUBLIC.TODO_CATEGORY (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CATE_NAME VARCHAR(255) NOT NULL,
	USERS_ID BIGINT NOT NULL,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	CONSTRAINT TODO_CATEGORY_PK PRIMARY KEY (ID),
	CONSTRAINT TODO_CATEGORY_FK FOREIGN KEY (USERS_ID) REFERENCES PUBLIC.TODO_USERS(ID)
);

# 유저 그룹 테이블 생성
CREATE TABLE PUBLIC.USER_GROUP (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	UG_NAME VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	CONSTRAINT USER_GROUP_PK PRIMARY KEY (ID)
);

# 유저 - 유저 그룹 매칭 테이블 생성
CREATE TABLE PUBLIC.USER_GROUP_RELATION (
	ID BIGINT NOT NULL,
	TU_ID BIGINT NOT NULL,
	UG_ID BIGINT NOT NULL,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	CONSTRAINT USER_GROUP_RELATION_PK PRIMARY KEY (ID),
	CONSTRAINT USER_GROUP_RELATION_FK FOREIGN KEY (TU_ID) REFERENCES PUBLIC.TODO_USERS(ID),
	CONSTRAINT USER_GROUP_RELATION_FK_1 FOREIGN KEY (UG_ID) REFERENCES PUBLIC.USER_GROUP(ID)
);

# 할일 테이블 생성
CREATE TABLE PUBLIC.TODO_WORK (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TW_TITLE VARCHAR(255) NOT NULL,
	TW_CONTENTS LONGTEXT,
	TW_START TIMESTAMP NOT NULL,
	TW_END TIMESTAMP,
	GROUP_ID BIGINT,
	TU_ID BIGINT NOT NULL,
	CATEGORY_ID BIGINT NOT NULL,
	TW_CHECK TINYINT DEFAULT 0 NOT NULL,
	CONSTRAINT TODO_WORK_PK PRIMARY KEY (ID),
	CONSTRAINT TODO_WORK_FK FOREIGN KEY (TU_ID) REFERENCES PUBLIC.TODO_USERS(ID),
	CONSTRAINT TODO_WORK_FK_1 FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.USER_GROUP(ID),
	CONSTRAINT TODO_WORK_FK_2 FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.TODO_CATEGORY(ID)
);




