# 유저테이블 생성
CREATE TABLE PUBLIC.TODO_USERS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERS_ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT TODO_USERS_PK PRIMARY KEY (ID)
);

# 카테고리 테이블 생성
CREATE TABLE PUBLIC.TODO_CATEGORY (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CATE_NAME VARCHAR(255) NOT NULL,
	USERS_ID BIGINT NOT NULL,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	CONSTRAINT TODO_CATEGORY_PK PRIMARY KEY (ID),
	CONSTRAINT TODO_CATEGORY_FK FOREIGN KEY (USERS_ID) REFERENCES PUBLIC.TODO_USERS(ID)
);


